inference_templates = {
    "painted_on_examples":[
        "cat {} stone",
        "cat {} vase",
        "hamburger {} canvas",
        "spiderman {} building",
        "michael jackson {} stone",
        "michael jackson {} wall"
    ],
    "carved_by_examples":[
        "cat {} jade",
        "cat {} clay",
        "cat {} wood",
        "rose {} carrot",
        "rose {} glass",
        "rose {} paper",
    ],
    "inside_examples":[
        "cat {} bowl",
        "cat {} box",
        "hamster {} cup",
        "hamster {} vase",
        "spiderman {} basket",
        "ocean {} pot",
    ],
    "shake_hands_examples":[
        "cat {} dog",
        "frog {} bear",
        "Donald Trump {} Obama",
        "man {} woman",
        "monkey {} cat",
        "bear {} monkey",
    ],
    "pick_up_examples":
    [
        
        "A robot {} a strawberry",
        "A robot arm {} a strawberry",
        "A robot arm {} a strawberry on a table",
        "A robot {} a strawberry on a table",
        "A robot {} a strawberry on a table, indoor scene",
        "A robot arm {} a small strawberry on a table",
        "A robot arm {} a small strawberry on a table, indoor scene",
        "A photo of a robot {} a strawberry",
        "A photo of a robot arm {} a strawberry",
        "A photo of a robot arm {} a strawberry on a table",
        "A photo of a robot {} a strawberry on a table",
        "A photo of a robot {} a strawberry on a table, indoor scene",
        "A photo of a robot arm {} a small strawberry on a table",
        "A photo of a robot arm {} a small strawberry on a table, indoor scene",
        "An image of a robot {} a strawberry",
        "An image of a robot arm {} a strawberry",
        "An image of a robot arm {} a strawberry on a table",
        "An image of a robot {} a strawberry on a table",
        "An image of a robot {} a strawberry on a table, indoor scene",
        "An image of a robot arm {} a small strawberry on a table",
        "An image of a robot arm {} a small strawberry on a table, indoor scene",
        
        
        "A photo of a robot {} a tennis ball on a table, indoor scene",
        "A photo of a robot arm {} a tennis ball on a table, indoor scene",
        "A photo of a boy {} a tennis ball on a table, indoor scene",
        "A photo of a girl {} a tennis ball on a table, indoor scene",
        "A photo of a grandpa {} a tennis ball on a table, indoor scene",
        "A photo of a monkey {} a tennis ball on a table, indoor scene",
        "A photo of a baby {} a tennis ball on a table, indoor scene",
        "A photo of a otter {} a tennis ball on a table, indoor scene",
        "A photo of Donald Trump {} a tennis ball on a table, indoor scene",
        
        
        "A photo of a robot {} a baseball on a table, indoor scene",
        "A photo of a robot arm {} a baseball on a table, indoor scene",
        "A photo of a boy {} a baseball on a table, indoor scene",
        "A photo of a girl {} a baseball on a table, indoor scene",
        "A photo of a grandpa {} a baseball on a table, indoor scene",
        "A photo of a monkey {} a baseball on a table, indoor scene",
        "A photo of a baby {} a baseball on a table, indoor scene",
        "A photo of a otter {} a baseball on a table, indoor scene",
        "A photo of Donald Trump {} a baseball on a table, indoor scene",
        
        "A photo of a robot {} a bottle on a table, indoor scene",
        "A photo of a robot arm {} a bottle on a table, indoor scene",
        "A photo of a boy {} a bottle on a table, indoor scene",
        "A photo of a girl {} a bottle on a table, indoor scene",
        "A photo of a grandpa {} a bottle on a table, indoor scene",
        "A photo of a monkey {} a bottle on a table, indoor scene",
        "A photo of a baby {} a bottle on a table, indoor scene",
        "A photo of Donald Trump {} a bottle on a table, indoor scene",
        
        "A photo of a robot {} a lemon on a table, indoor scene",
        "A photo of a robot arm {} a lemon on a table, indoor scene",
        "A photo of a boy {} a lemon on a table, indoor scene",
        "A photo of a girl {} a lemon on a table, indoor scene",
        "A photo of a grandpa {} a lemon on a table, indoor scene",
        "A photo of a monkey {} a lemon on a table, indoor scene",
        "A photo of a baby {} a lemon on a table, indoor scene",
        "A photo of Donald Trump {} a lemon on a table, indoor scene",
        
        "A photo of a robot {} a World Cup on a table, indoor scene",
        "A photo of a robot arm {} a World Cup on a table, indoor scene",
        "A photo of a boy {} a World Cup on a table, indoor scene",
        "A photo of a girl {} a World Cup on a table, indoor scene",
        "A photo of a grandpa {} a World Cup on a table, indoor scene",
        "A photo of a monkey {} a World Cup on a table, indoor scene",
        "A photo of a baby {} a World Cup on a table, indoor scene",
        "A photo of Donald Trump {} a World Cup on a table, indoor scene",
    ],
    "simple_pickup_templates":
    [
    "A photo of a robot {} an iPhone on a table, indoor scene",
    "A photo of a robot arm {} an iPhone on a table, indoor scene",
    "A photo of a boy {} an iPhone on a table, indoor scene",
    "A photo of a girl {} an iPhone on a table, indoor scene",
    "A photo of a grandpa {} an iPhone on a table, indoor scene",
    "A photo of a monkey {} an iPhone on a table, indoor scene",
    "A photo of a baby {} an iPhone on a table, indoor scene",
    "A photo of Donald Trump {} an iPhone on a table, indoor scene",
    
    
    "A photo of a robot {} an apple on a table, indoor scene",
    "A photo of a robot arm {} an apple on a table, indoor scene",
    "A photo of a boy {} an apple on a table, indoor scene",
    "A photo of a girl {} an apple on a table, indoor scene",
    "A photo of a grandpa {} an apple on a table, indoor scene",
    "A photo of a monkey {} an apple on a table, indoor scene",
    "A photo of a baby {} an apple on a table, indoor scene",
    "A photo of Donald Trump {} an apple on a table, indoor scene",
    
    "A photo of a robot {} a bottle on a table, indoor scene",
    "A photo of a robot arm {} a bottle on a table, indoor scene",
    "A photo of a boy {} a bottle on a table, indoor scene",
    "A photo of a girl {} a bottle on a table, indoor scene",
    "A photo of a grandpa {} a bottle on a table, indoor scene",
    "A photo of a monkey {} a bottle on a table, indoor scene",
    "A photo of a baby {} a bottle on a table, indoor scene",
    "A photo of Donald Trump {} a bottle on a table, indoor scene",
    
    "A photo of a robot {} a vase on a table, indoor scene",
    "A photo of a robot arm {} a vase on a table, indoor scene",
    "A photo of a boy {} a vase on a table, indoor scene",
    "A photo of a girl {} a vase on a table, indoor scene",
    "A photo of a grandpa {} a vase on a table, indoor scene",
    "A photo of a monkey {} a vase on a table, indoor scene",
    "A photo of a baby {} a vase on a table, indoor scene",
    "A photo of Donald Trump {} a vase on a table, indoor scene",
    
    "A photo of a robot {} a trophy cup on a table, indoor scene",
    "A photo of a robot arm {} a trophy cup on a table, indoor scene",
    "A photo of a boy {} a trophy cup on a table, indoor scene",
    "A photo of a girl {} a trophy cup on a table, indoor scene",
    "A photo of a grandpa {} a trophy cup on a table, indoor scene",
    "A photo of a monkey {} a trophy cup on a table, indoor scene",
    "A photo of a baby {} a trophy cup on a table, indoor scene",
    "A photo of Donald Trump {} a trophy cup on a table, indoor scene",
    
    "A photo of a rabit {} a carrot, on the field",
    "A photo of a lady {} a sunglasses, on the beach",
    "A photo of Michael Jackson {} a ring, on a table",
    "A photo of Taylor Swift {} a wallet, on the ground",
    "A photo of a panda {} a stone, in the forest",
    "A photo of a cleaner {} a waste paper, on the ground",
    "A photo of a bird {} a cherry, on the tree",
    "A photo of a cat {} a ball of yarn, on the wooden floor",
    "A photo of a otter {} a fish, by the lake",],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],
    
    "sd-lift-templates":
    [
    "A photo of a robot lift an iPhone on a table, indoor scene",
    "A photo of a robot arm lift an iPhone on a table, indoor scene",
    "A photo of a boy lift an iPhone on a table, indoor scene",
    "A photo of a girl lift an iPhone on a table, indoor scene",
    "A photo of a grandpa lift an iPhone on a table, indoor scene",
    "A photo of a monkey lift an iPhone on a table, indoor scene",
    "A photo of a baby lift an iPhone on a table, indoor scene",
    "A photo of Donald Trump lift an iPhone on a table, indoor scene",
    
    
    "A photo of a robot lift an apple on a table, indoor scene",
    "A photo of a robot arm lift an apple on a table, indoor scene",
    "A photo of a boy lift an apple on a table, indoor scene",
    "A photo of a girl lift an apple on a table, indoor scene",
    "A photo of a grandpa lift an apple on a table, indoor scene",
    "A photo of a monkey lift an apple on a table, indoor scene",
    "A photo of a baby lift an apple on a table, indoor scene",
    "A photo of Donald Trump lift an apple on a table, indoor scene",
    
    "A photo of a robot lift a bottle on a table, indoor scene",
    "A photo of a robot arm lift a bottle on a table, indoor scene",
    "A photo of a boy lift a bottle on a table, indoor scene",
    "A photo of a girl lift a bottle on a table, indoor scene",
    "A photo of a grandpa lift a bottle on a table, indoor scene",
    "A photo of a monkey lift a bottle on a table, indoor scene",
    "A photo of a baby lift a bottle on a table, indoor scene",
    "A photo of Donald Trump lift a bottle on a table, indoor scene",
    
    "A photo of a robot lift a vase on a table, indoor scene",
    "A photo of a robot arm lift a vase on a table, indoor scene",
    "A photo of a boy lift a vase on a table, indoor scene",
    "A photo of a girl lift a vase on a table, indoor scene",
    "A photo of a grandpa lift a vase on a table, indoor scene",
    "A photo of a monkey lift a vase on a table, indoor scene",
    "A photo of a baby lift a vase on a table, indoor scene",
    "A photo of Donald Trump lift a vase on a table, indoor scene",
    
    "A photo of a robot lift a trophy cup on a table, indoor scene",
    "A photo of a robot arm lift a trophy cup on a table, indoor scene",
    "A photo of a boy lift a trophy cup on a table, indoor scene",
    "A photo of a girl lift a trophy cup on a table, indoor scene",
    "A photo of a grandpa lift a trophy cup on a table, indoor scene",
    "A photo of a monkey lift a trophy cup on a table, indoor scene",
    "A photo of a baby lift a trophy cup on a table, indoor scene",
    "A photo of Donald Trump lift a trophy cup on a table, indoor scene",
    
    "A photo of a rabit lift a carrot, on the field",
    "A photo of a lady lift a sunglasses, on the beach",
    "A photo of Michael Jackson lift a ring, on a table",
    "A photo of Taylor Swift lift a wallet, on the ground",
    "A photo of a panda lift a stone, in the forest",
    "A photo of a cleaner lift a waste paper, on the ground",
    "A photo of a bird lift a cherry, on the tree",
    "A photo of a cat lift a ball of yarn, on the wooden floor",
    "A photo of a otter lift a fish, by the lake",],

    "simple_pull_drawer_templates":
    [
    "A photo of a robot {} a drawer of a cabinet",
    "A photo of a robot arm {} a drawer of a cabinet",
    "A photo of a boy {} a drawer of a cabinet",
    "A photo of a girl {} a drawer of a cabinet",
    "A photo of a grandpa {} a drawer of a cabinet",
    "A photo of a monkey {} a drawer of a cabinet",
    "A photo of a baby {} a drawer of a cabinet",
    "A photo of Donald Trump {} a drawer of a cabinet",
    
    
    "A photo of a robot {} a drawer of a desk",
    "A photo of a robot arm {} a drawer of a desk",
    "A photo of a boy {} a drawer of a desk",
    "A photo of a girl {} a drawer of a desk",
    "A photo of a grandpa {} a drawer of a desk",
    "A photo of a monkey {} a drawer of a desk",
    "A photo of a baby {} a drawer of a desk",
    "A photo of Donald Trump {} a drawer of a desk",
    
    "A photo of a rabit {} a drawer of a box",
    "A photo of a lady {} a drawer of a box",
    "A photo of Michael Jackson {} a drawer of a box",
    "A photo of Taylor Swift {} a drawer of a box",
    "A photo of a panda {} a drawer of a box",
    "A photo of a cleaner {} a drawer of a box",
    "A photo of a bird {} a drawer of a box",
    "A photo of a cat {} a drawer of a box",
    "A photo of a otter {} a drawer of a box",],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],

    "sd-pull-drawer-templates":
    [
    "A photo of a robot pull out a drawer of a cabinet",
    "A photo of a robot arm pull out a drawer of a cabinet",
    "A photo of a boy pull out a drawer of a cabinet",
    "A photo of a girl pull out a drawer of a cabinet",
    "A photo of a grandpa pull out a drawer of a cabinet",
    "A photo of a monkey pull out a drawer of a cabinet",
    "A photo of a baby pull out a drawer of a cabinet",
    "A photo of Donald Trump pull out a drawer of a cabinet",
    
    
    "A photo of a robot pull out a drawer of a desk",
    "A photo of a robot arm pull out a drawer of a desk",
    "A photo of a boy pull out a drawer of a desk",
    "A photo of a girl pull out a drawer of a desk",
    "A photo of a grandpa pull out a drawer of a desk",
    "A photo of a monkey pull out a drawer of a desk",
    "A photo of a baby pull out a drawer of a desk",
    "A photo of Donald Trump pull out a drawer of a desk",
    
    "A photo of a rabit pull out a drawer of a box",
    "A photo of a lady pull out a drawer of a box",
    "A photo of Michael Jackson pull out a drawer of a box",
    "A photo of Taylor Swift pull out a drawer of a box",
    "A photo of a panda pull out a drawer of a box",
    "A photo of a cleaner pull out a drawer of a box",
    "A photo of a bird pull out a drawer of a box",
    "A photo of a cat pull out a drawer of a box",
    "A photo of a otter pull out a drawer of a box",],
    
    "some_special_templates":[
    "A photo of a lady pull out a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson pull out a microphone, on a floor",
    "A photo of an otter pull out a fish in the water, by the lake",
    "A photo of a panda pull out a hat, in the forest",
        ],
    
    "simple_pull_door_templates":
    [
    "A photo of a robot {} the door of a refrigerator",
    "A photo of a robot arm {} the door of a refrigerator",
    "A photo of a boy {} the door of a refrigerator",
    "A photo of a girl {} the door of a refrigerator",
    "A photo of a grandpa {} the door of a refrigerator",
    "A photo of a monkey {} the door of a refrigerator",
    "A photo of a baby {} the door of a refrigerator",
    "A photo of Donald Trump {} the door of a refrigerator",
    
    
    "A photo of a robot {} the door of a safebox",
    "A photo of a robot arm {} a door of a safebox",
    "A photo of a boy {} a door of a safebox",
    "A photo of a girl {} a door of a safebox",
    "A photo of a grandpa {} a door of a safebox",
    "A photo of a monkey {} a door of a safebox",
    "A photo of a baby {} a door of a safebox",
    "A photo of Donald Trump {} a door of a safebox",
    
    "A photo of a rabit {} a door of a house",
    "A photo of a lady {} a door of a house",
    "A photo of Michael Jackson {} a door of a house",
    "A photo of Taylor Swift {} a door of a house",
    "A photo of a panda {} a door of a house",
    "A photo of a cleaner {} a ddoor of a house",
    "A photo of a bird {} a door of a house",
    "A photo of a cat {} a door of a house",
    "A photo of a otter {} a door of a house",],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],


    "sd_pull_door_templates":
    [
    "A photo of a robot open the door of a refrigerator",
    "A photo of a robot arm open the door of a refrigerator",
    "A photo of a boy open the door of a refrigerator",
    "A photo of a girl open the door of a refrigerator",
    "A photo of a grandpa open the door of a refrigerator",
    "A photo of a monkey open the door of a refrigerator",
    "A photo of a baby open the door of a refrigerator",
    "A photo of Donald Trump open the door of a refrigerator",
    
    
    "A photo of a robot open the door of a safebox",
    "A photo of a robot arm open a door of a safebox",
    "A photo of a boy open a door of a safebox",
    "A photo of a girl open a door of a safebox",
    "A photo of a grandpa open a door of a safebox",
    "A photo of a monkey open a door of a safebox",
    "A photo of a baby open a door of a safebox",
    "A photo of Donald Trump open a door of a safebox",
    
    "A photo of a rabit open a door of a house",
    "A photo of a lady open a door of a house",
    "A photo of Michael Jackson open a door of a house",
    "A photo of Taylor Swift open a door of a house",
    "A photo of a panda open a door of a house",
    "A photo of a cleaner open a ddoor of a house",
    "A photo of a bird open a door of a house",
    "A photo of a cat open a door of a house",
    "A photo of a otter open a door of a house",],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],
    # please put your customized templates from here
     "sd_pull_door_templates_v2":
    [
    "A photo of a boy open the door of a refrigerator",
    "A photo of a girl open the door of a refrigerator",
    "A photo of a grandpa open the door of a refrigerator",
    "A photo of a monkey open the door of a refrigerator",
    "A photo of a baby open the door of a refrigerator",
    "A photo of Donald Trump open the door of a refrigerator",
    
    "A photo of a lady open a door of a bedroom",
    "A photo of Michael Jackson open a door of a bedroom",
    "A photo of Taylor Swift open a door of a bedroom",
    "A photo of a panda open a door of a bedroom",
    "A photo of a cleaner open a ddoor of a bedroom",
    "A photo of a bird open a door of a bedroom",
    "A photo of a cat open a door of a bedroom",
    
    "A photo of a lady open a door of a cabinet",
    "A photo of Michael Jackson open a door of a cabinet",
    "A photo of Taylor Swift open a door of a cabinet",
    "A photo of a panda open a door of a cabinet",
    "A photo of a cleaner open a ddoor of a cabinet",
    ],
    
     "sd_pull_door_templates_v3":
    [
    "A photo of a lady open a door of a cabinet. About 30 degrees, indoor scene, front view, the lady is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    "A photo of a lady open a door of a cabinet. About 30 degrees, indoor scene, left side view, the lady is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    
    "A photo of Michael Jackson open a door of a cabinet. About 90 degrees, indoor scene, front view, Michael Jackson is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    "A photo of Michael Jackson open a door of a cabinet. About 90 degrees, indoor scene, left side view, Michael Jackson is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    
    "A photo of a boy open a door of a cabinet. About 30 degrees, indoor scene, front view, the boy is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    "A photo of a boy open a door of a cabinet. About 30 degrees, indoor scene, left side view, the boy is the at the bottom of the photo. It touches the right door of the cabinet, which is at the middle of the image. The cabinet is made of brown wooden.",
    ],
    
    "some_special_templates":[
    "A photo of a lady {} a sunglasses, on the ground by the beach",
    "A photo of Michael Jackson {} a microphone, on a floor",
    "A photo of an otter {} a fish in the water, by the lake",
    "A photo of a panda {} a hat, in the forest",
        ],
}
